- name: install redis-server
  apt:
    name: redis-server
    state: present

- name: template /etc/redis/redis.conf
  template:
    dest: /etc/redis/redis.conf
    src: templates/etc/redis/redis.conf.j2
    owner: redis
    group: root
    mode: 0640
  notify: restart redis
